version: "3.9"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE # argumento para no mostrar errores turbinas
    restart: always
    environment:
      - MYSQL_DATABASE=digifinanz
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./database_files:/var/lib/mysql